AuthenticationAuthorizationFE/Models/ErrorViewModel.cs
namespace AuthenticationAuthorizationFE.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AuthenticationAuthorizationFE/Models/IBusinessResult.cs
using System.Text.Json.Serialization;

namespace EquipmentsBusiness.Base;

public interface IBusinessResult
{
    bool IsSuccess { get; set; }
    string? Message { get; set; }
    object? Data { get; set; }
}
public class BusinessResult : IBusinessResult
{
    public bool IsSuccess { get; set; }
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Message { get; set; }
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Data { get; set; }

    public BusinessResult()
    {
    }

    public BusinessResult(bool isSuccess, string? message, object? data)
    {
        IsSuccess = isSuccess;
        Message = message;
        Data = data;
    }

    public BusinessResult(bool isSuccess, string message)
    {
        IsSuccess = isSuccess;
        Message = message;
    }

    public BusinessResult(bool isSuccess, object data)
    {
        IsSuccess = isSuccess;
        Data = data;
    }
}

AuthenticationAuthorizationFE/Controllers/AccountController.cs
using System.Net;
using System.Text;
using AuthenticationAuthorizationFE.Request;
using AuthenticationAuthorizationFE.Response;
using EquipmentsBusiness.Base;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace AuthenticationAuthorizationFE.Controllers;

public class AccountController : Controller
{
    private readonly string API_URL_ENDPOINT = "https://localhost:7088/api/v1/Account";

    public AccountController()
    {
    }

    public async Task<IActionResult> Index()
    {
        return View();
    }


    [HttpPost]
    public async Task<IActionResult> Login([FromBody] LoginRequest request)
    {
        try
        {
            using (var httpClient = new HttpClient())
            {
                var json = JsonConvert.SerializeObject(request);
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                using (var response = await httpClient.PostAsync(API_URL_ENDPOINT + "/Login", content))
                {
                    if (response.IsSuccessStatusCode)
                    {
                        var contentString = await response.Content.ReadAsStringAsync();
                        var data = JsonConvert.DeserializeObject<BusinessResult>(contentString)!.Data!;
                        var loginResponse = JsonConvert.DeserializeObject<LoginResponse>(data.ToString()!);
                        HttpContext.Session.SetString("accessToken", loginResponse!.Token);
                        HttpContext.Session.SetString("role", loginResponse.Role);
                        return Ok(loginResponse);
                    }

                    if (response.StatusCode == HttpStatusCode.Unauthorized)
                    {
                        var contentString = await response.Content.ReadAsStringAsync();
                        var errorMessage = JsonConvert.DeserializeObject<BusinessResult>(contentString)!.Message;
                        return BadRequest(errorMessage);
                    }
                    else
                    {
                        var errorMessage = $"Request failed with status code: {response.StatusCode} and reason: {response.ReasonPhrase}";
                        return StatusCode((int)response.StatusCode, errorMessage);
                    }
                }
            }
        }
        catch (Exception ex)
        {
            return StatusCode(500, $"Internal server error: {ex.Message}");
        }
    }
}

AuthenticationAuthorizationFE/Controllers/EquipmentController.cs
using System.Net;
using AuthenticationAuthorizationFE.Response;
using EquipmentsBusiness.Base;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace AuthenticationAuthorizationFE.Controllers;

public class EquipmentController : Controller

{
    private readonly string API_URL_ENDPOINT = "https://localhost:7088/api/v1/Equipment";

    public EquipmentController()
    {
    }

    public async Task<IActionResult> Index()
    {
        return View();
    }

    [HttpGet]
    public async Task<IActionResult> GetAll()
    {
        try
        {
            using (var httpClient = new HttpClient())
            {
                var token = HttpContext.Session.GetString("accessToken") ?? "";
                // Set the Authorization header with the Bearer token
                httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);
                using (var response = await httpClient.GetAsync(API_URL_ENDPOINT + "/GetAll"))
                {
                    if (response.IsSuccessStatusCode)
                    {
                        var contentString = await response.Content.ReadAsStringAsync();
                        var data = JsonConvert.DeserializeObject<BusinessResult>(contentString)!.Data!;
                        var responses = JsonConvert.DeserializeObject<List<EquipmentResponse>>(data.ToString()!);
                        return Ok(responses);
                    }

                    if (response.StatusCode is HttpStatusCode.Unauthorized or HttpStatusCode.Forbidden)
                    {
                        var contentString = await response.Content.ReadAsStringAsync();
                        var errorMessage = JsonConvert.DeserializeObject<BusinessResult>(contentString)!.Message;
                        return BadRequest(errorMessage);
                    }

                    else
                    {
                        var errorMessage = $"Request failed with status code: {response.StatusCode} and reason: {response.ReasonPhrase}";
                        return StatusCode((int)response.StatusCode, errorMessage);
                    }
                }
            }
        }
        catch (Exception ex)
        {
            return StatusCode(500, $"Internal server error: {ex.Message}");
        }
    }
}

AuthenticationAuthorizationFE/Controllers/HomeController.cs
using AuthenticationAuthorizationFE.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AuthenticationAuthorizationFE.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        [HttpGet]
        public IActionResult Logout()
        {
            // Clear the session
            HttpContext.Session.Clear();

            // Redirect to the homepage
            return RedirectToAction("Index", "Home");
        }
    }
}

AuthenticationAuthorizationFE/Controllers/RoomController.cs
using System.Text;
using AuthenticationAuthorizationFE.Response;
using EquipmentsBusiness.Base;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace AuthenticationAuthorizationFE.Controllers;

public class RoomController : Controller

{
    private readonly string API_URL_ENDPOINT = "https://localhost:7088/api/v1/Room";

    public RoomController()
    {
    }

    public async Task<IActionResult> Index()
    {
        return View();
    }

    [HttpGet]
    public async Task<IActionResult> GetAll()
    {
        try
        {
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(API_URL_ENDPOINT + "/GetAll"))
                {
                    if (response.IsSuccessStatusCode)
                    {
                        var contentString = await response.Content.ReadAsStringAsync();
                        var data = JsonConvert.DeserializeObject<BusinessResult>(contentString)!.Data!;
                        var responses = JsonConvert.DeserializeObject<List<RoomResponse>>(data.ToString()!);
                        return Ok(responses);
                    }
                    var errorMessage = $"Request failed with status code: {response.StatusCode} and reason: {response.ReasonPhrase}";
                    return StatusCode((int)response.StatusCode, errorMessage);
                }
            }
        }
        catch (Exception ex)
        {
            return StatusCode(500, $"Internal server error: {ex.Message}");
        }
    }
}

AuthenticationAuthorizationFE/Views/Equipment/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
<style>
    #topUpModal .modal-dialog {
        max-width: 60%; /* Adjust this value as needed */
    }
</style>
<div class="row">
    <div class="col-md-10">
        <h2 class="display-8">Room List</h2>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr class="card-header">
                    <th class="card-title text-center">ID</th>
                    <th class="card-title text-center">Code</th>
                    <th class="card-title text-center">Name</th>
                    <th class="card-title text-center">Description</th>
                    <th class="card-title text-center">Model</th>
                    <th class="card-title text-center">SupplierName</th>
                    <th class="card-title text-center">Quantity</th>
                    <th class="card-title text-center">RoomName</th>
                    <th class="card-title text-center">Location</th>
                </tr>
            </thead>
            <tbody class="tblList">
            </tbody>
        </table>
    </div>
</div>

@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            loadData();          
        });

        function loadData() {
            var spin = document.getElementById('spinner-overlay');
            $.ajax({
                url: '@Url.Action("GetAll", "Equipment")',
                type: "GET",
                contentType: "application/json;charset=utf-8",
                dataType: "json",
                success: function (result) {
                    var html = '';
                    // console.log(result);
                    $.each(result, function (key, item) {
                        console.log(item);
                        html += '<tr>';
                        html += '<td>' + item.id + '</td>';
                        html += '<td>' + item.code + '</td>';
                        html += '<td>' + item.name + '</td>';
                        html += '<td>' + item.description + '</td>';
                        html += '<td>' + item.model + '</td>';
                        html += '<td>' + item.supplierName + '</td>';
                        html += '<td>' + item.quantity + '</td>';
                        html += '<td>' + item.roomName + '</td>';
                        html += '<td>' + item.location + '</td>';

                        html += '</tr>';
                    });
                    $('.tblList').html(html);
                },
                error: function (xhr, error) {
                    alert(xhr.responseText);
                    window.location.href = '/';
                }
            });
        }

    

    </script>
}

AuthenticationAuthorizationFE/Views/Home/Index.cshtml
@model AuthenticationAuthorizationFE.Request.LoginRequest
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Login</h1>
    <div style="align-items: center; width: 400px; margin-left: auto; margin-right: auto; ">
        <div class="d-flex flex-column align-items-center">
            <div class="form-group" style="display: flex;  align-items: center; margin-bottom: 10px;">
                <label style="margin-right: 8px;">Username:</label>
                <input type="text" class="form-control" id="username" name="username" placeholder="Username" required style="flex: 1; max-width: 200px;">
            </div>
            <div class="form-group" style="display: flex; align-items: center;">
                <label style="margin-right: 10px;">Password:</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Password" required style="flex: 1; max-width: 200px;">
            </div>
        </div>

        <span id="errorMessage" class="text-danger"></span>
        <br />
        <div style="margin-top: 10px; vertical-align:central; display:flex; justify-content:space-around">
            <button type="submit" class="btn btn-primary" onclick="login();">Login</button>
        </div>
    </div>
</div>

@section scripts {
    <script type="text/javascript">
        function login() {
            var loginRequest = {
                Password: $('#password').val(),
                Username: $('#username').val(),
            };
            $.ajax({
                type: 'POST',
                url: '@Url.Action("Login", "Account")',
                contentType: 'application/json;charset=utf-8',
                dataType: "json",
                data: JSON.stringify(loginRequest),
                success: function (result) {
                    console.log(result);
                    window.location.href = '/Equipment/Index';
                },
                error: function (xhr, error) {
                    console.log(xhr.responseText);
                    $('#errorMessage').text(xhr.responseText);
                }
            });
        }
    </script>
}

AuthenticationAuthorizationFE/Views/Room/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
<style>
    #topUpModal .modal-dialog {
        max-width: 60%; /* Adjust this value as needed */
    }
</style>
<div class="row">
    <div class="col-md-10">
        <h2 class="display-8">Room List</h2>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr class="card-header">
                    <th class="card-title text-center">ID</th>
                    <th class="card-title text-center">RoomName</th>
                    <th class="card-title text-center">Location</th>
                    <th class="card-title text-center">Status</th>
                </tr>
            </thead>
            <tbody class="tblList">
            </tbody>
        </table>
    </div>
</div>

@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            loadData();          
        });

        function loadData() {
            var spin = document.getElementById('spinner-overlay');
            $.ajax({
                url: '@Url.Action("GetAll", "Room")',
                type: "GET",
                contentType: "application/json;charset=utf-8",
                dataType: "json",
                success: function (result) {
                    var html = '';
                    // console.log(result);
                    $.each(result, function (key, item) {
                        console.log(item);
                        html += '<tr>';
                        html += '<td>' + item.id + '</td>';
                        html += '<td>' + item.name + '</td>';
                        html += '<td>' + item.location + '</td>';
                        html += '<td>' + item.status + '</td>';
                        html += '</tr>';
                    });
                    $('.tblList').html(html);
                },
                error: function (xhr, error) {
                    console.log(xhr.responseText);
                    $('#errorMessage').text(xhr.responseText);
                }
            });
        }

    

    </script>
}

AuthenticationAuthorizationFE/Views/Shared/_Layout.cshtml
@{
    var httpContext = ViewContext.HttpContext;
    var role = httpContext.Session.GetString("role");
    ViewData["Role"] = role;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - AuthenticationAuthorizationFE</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/AuthenticationAuthorizationFE.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AuthenticationAuthorizationFE</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="/Room/Index">Room</a>
                    </li>
                    @if (role != null && (role == "Admin" || role == "Manager" || role == "Staff" || role == "Student"))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - AuthenticationAuthorizationFE - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>